### ISSUE TITLE
Null pointer exception when retrieving card multiIds

### ISSUE THREAD

**Issue by Omabytes** [ForOhForError/CustomCardCam#4]
Below error in console when attempting to save a set. Loading bar sticks halfway.

Exception in thread "Thread-4" java.lang.NullPointerException
        at forohfor.scryfall.api.Card.<init>(Card.java:73)
        at forohfor.scryfall.api.MTGCardQuery.getCardsFromURI(MTGCardQuery.java:142)
        at forohfor.scryfall.api.MTGCardQuery.search(MTGCardQuery.java:67)
        at forohfor.scryfall.api.MTGCardQuery.toCardList(MTGCardQuery.java:49)
        at FileOperations.getMultiIds(FileOperations.java:218)
        at FileOperations.decklistToIds(FileOperations.java:275)
        at MTGCustomCardCam$SetMakeThread.doSetMake(MTGCustomCardCam.java:207)
        at MTGCustomCardCam$SetMakeThread.run(MTGCustomCardCam.java:188)

**Comment by Omabytes** [comment]
All other buttons on the UI work despite the loading bar being stuck.
